# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_SignUp',
            new_name='UserSignUp',
        ),
    ]
